### ISSUE TITLE
Is it possible to have the slides.

### ISSUE THREAD

**Issue by sperezconesa** [AllenDowney/CompStats#7]
Hello,
I have seen the tutorial on youtube and I really loved it! Could it be possible to have the slides? 
Thank you very much!
Best regards,
Sergio

**Comment by AllenDowney** [comment]
Yes, probably.  Which tutorial?  

Usually I put a link to the slides in the slides, so you might be able to get it from the video.

**Comment by sperezconesa** [comment]
It's I OK. I finally took it from the video. :)
Thanks anyway!
